---
#
# Ansible managed
#
repository:
  description: tune ext3 and ext4 filesystems using tune2fs.
  homepage: https://buluma.github.io/
  topics: tune2fs, ansible, molecule, tox, playbook, hacktoberfest
